apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: aerolink
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: ghcr.io/savindufernando/enterprise-cloud-2-booking_service:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: aerolink-config
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: aerolink
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: http
